const ActionType = {
    CHANGEOPT:'CHANGEOPT',
    CALVALUE:'CALVALUE',
    PUSHLOG:'PUSHLOG',
    REVERTLOG:'REVERLOG',
    FECTHHISTORY:'FECTHHISTORY',
    FETCHDATASUCCESS:'FETCHDATASUCCESS',
    SAVEHISTORY:'SAVEHISTORY'  
}

module.exports = ActionType;